### ISSUE TITLE
Assets Page

### ISSUE THREAD

**Issue by marcgs** [agera-edc/EDCDataDashboard#15]
## Description

The current "Data Publisher" page needs to be adapted, following the same UI pattern as the "Contract Definition Editor" page. All existing assets must be listed and a button allows creating new assets.

## Acceptance Criteria
- [ ] Assets page list current Assets
- [ ] Assets page allows creating new Assets with all required information

## Tasks
- [ ] Data Publisher page is renamed to "Assets"
- [ ] Current Assets are listed
- [ ] Button and mask to create new assets with all the required inputs
