### ISSUE TITLE
Contract Definitions Page

### ISSUE THREAD

**Issue by marcgs** [agera-edc/EDCDataDashboard#16]
Feature #14

## Description

The current "Contract Definitions" page supports creating new contract definitions by introducing the "asset property", "operator and "value" triplet as text. This is not user-friendly and must be improved.

## Acceptance Criteria
- [x] Improve UI to allow selection from available assets (multi-selection)

## Tasks
- [x] Rename page from "Contract Definition Editor" to "Contract Definitions"
- [x] Improve UI to allow selection from available assets (multi-selection)
