### ISSUE TITLE
Getting Started Page

### ISSUE THREAD

**Issue by zeier** [agera-edc/EDCDataDashboard#17]
Feature #14 

## Description

The `Getting Started` page currently contains outdated information, based on the initial implementation where the communication with the EDC was done through an extension.

We want to update this page and mention that it provides a development UI for the `DataManagementAPI`.

## Acceptance Criteria

- [x] `Getting Started` page is updated to reflect the current state of implementation
- [x] Text contains information that it is a development UI for the `DataManagementAPI`
- [x] Page contains a link to the `DataManagementAPI` specification

## Tasks

- [x] Update text on the `Getting Started` page
