### ISSUE TITLE
Date/Time of transfers on Transfer History page

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/EDCDataDashboard#20]
Feature #14 
Requires EDC change https://github.com/agera-edc/DataSpaceConnector/issues/264

## Descrioption

Add transfer Date/Time on Transfer History Page. This will be helpful to easily see which one was the most recent transfer and which is 2nd last and so on. Currently it is not clearly visible that which one is most recent transfer.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/555114/167148369-5a4c4718-50d7-4ab9-8e22-da725ca2979e.png">

- Transfer Created
- Transfer Updated

## Acceptance Criteria

- [ ] The UI shows timestamps for each transfer process

## Tasks

- [ ] Add timestamps to the DTOs in case they are missing
- [ ] Add timestamps to the UI

**Comment by paullatzelsperger** [comment]
@algattik AFAIK you're assigned the upstream DM Api issue. For the frontend I'll introduce two new properties on the DTO `creationDate` and `lastUpdated` containing the number of milliseconds since the Epoch of 01-01-1970.

**Comment by algattik** [comment]
@paullatzelsperger see https://github.com/agera-edc/DataSpaceConnector/pull/265, could we sign the field names please?

**Comment by paullatzelsperger** [comment]
done and comment updated.
